# -*- coding: utf-8 -*-
# Configuración de autenticación para Maxwell AI
# Este archivo debe guardarse con codificación UTF-8

credentials:
  usernames:
    admin:
      email: admin@infolytics.ai
      name: Administrador
      password: $2b$12$VmYV4svbZzIMmbVDUKdGF.VkxTVMbDxxux8nKCuBRXJP90Q9XLumW  # 4dm1n#M4xw3ll
    jdavila:
      email: jdavila@infolytics.ai
      name: Jeremías Dávila
      password: $2b$12$Tg/BLgiAq/gEJ9K40x1MVuyKlw1k/2qOUvx1vzJgAQ.YwaRhJi9Qm  # J3r3m14s#M4xw3ll

cookie:
  expiry_days: 1
  key: "maxwell_secure_cookie_key_2024"
  name: "maxwell_cookie"

security:
  max_login_attempts: 5
  block_duration_minutes: 5
  rate_limit_window_hours: 1
  max_requests_per_window: 100
  password_min_length: 8
  require_special_chars: true
  require_numbers: true
  require_uppercase: true
